import { API_BASES } from './endpoint.constant'

const PROJECT_SUBPATH = 'Project'
export const PROJECT_ENDPOINTS = {
  GETS: `${API_BASES.LOGIC}/${PROJECT_SUBPATH}/Gets`,
  GET: `${API_BASES.LOGIC}/${PROJECT_SUBPATH}/Get`,
  DISABLE: `${API_BASES.LOGIC}/${PROJECT_SUBPATH}/Disable`,
}

const MIGRATION_SUBPATH = '/Migration'

export const MIGRATION_ENDPOINTS = {
  MIGRATE: `${API_BASES.LOGIC}${MIGRATION_SUBPATH}/Migrate`,
  VERIFY: `${API_BASES.LOGIC}${MIGRATION_SUBPATH}/Verify`,
  GET_STATUS: `${API_BASES.LOGIC}${MIGRATION_SUBPATH}/GetMigrationStatus`,
} as const