<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <RootNamespace>BlocksTemplate.DomainService</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="CsvHelper"  />
    <PackageReference Include="FluentValidation"  />
    <PackageReference Include="Newtonsoft.Json"  />
    <PackageReference Include="SeliseBlocks.Genesis" />
    <PackageReference Include="SeliseBlocks.StorageDriver" />
	 <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>

</Project>
