import { API_BASES } from "@/constants/endpoint.constant";

const BLOCKS_UDS_BASE_URL = "https://dev-uds.blocksdevelopers.com";
const STORAGE_SUBPATH = "/Storage";
const FILES_SUBPATH = "/Files";

// Storage Configuration endpoints
export const STORAGE_CONFIG_ENDPOINTS = {
  GET_CONFIGS: `${BLOCKS_UDS_BASE_URL}${API_BASES.CLOUD_CONFIGURATION}${STORAGE_SUBPATH}/Gets`,
  SAVE_CONFIG: `${BLOCKS_UDS_BASE_URL}${API_BASES.CLOUD_CONFIGURATION}${STORAGE_SUBPATH}/Save`,
  DELETE_CONFIG: `${BLOCKS_UDS_BASE_URL}${API_BASES.CLOUD_CONFIGURATION}${STORAGE_SUBPATH}/Delete`,
} as const;

// Storage File endpoints
export const STORAGE_FILE_ENDPOINTS = {
  GET_FILE: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/GetFile`,
  DELETE_FILE: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/DeleteFile`,
  DELETE_FOLDER: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/DeleteFolder`,
  GET_PRESIGNED_URL: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/GetPreSignedUrlForUpload`,
  GET_FILES_INFO: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/GetFilesInfo`,
  UPDATE_FILE_ADDITIONAL_INFO: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/updateFileAdditionalInfo`,
  UPLOAD_TO_LOCAL_STORAGE: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/UploadFileToLocalStorage`,
  GET_DMS_FILE_AND_FOLDER: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/GetDmsFileAndFolder`,
  UPLOAD_DMS_FILE: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/UploadFile`,
  CREATE_FOLDER: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}${FILES_SUBPATH}/CreateFolder`,
  UPLOAD_PUBLIC_CERTIFICATE: `${BLOCKS_UDS_BASE_URL}${API_BASES.UDS}/Certificate/UploadCertificate`,
} as const;
